# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# > # this means to ignore newlines until "baseurl:"

# Site settings
title: Mithilesh Vaidya
full_name: Mithilesh Vaidya
author: Mithilesh Vaidya
email: vaidya.mithilesh@gmail.com
email2: mithilesh.vaidya@iitb.ac.in
description: An attempt to summarise my learnings in the field of Machine Learning and other interesting topics
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://methi1999.github.io" # the base hostname & protocol for your site
github_username:  methi1999
linkedin_username: mithileshvaidya
include: ['_pages']
footer-links-active:
  stackoverflow: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Google services
google_analytics: UA-172062065-1

#theme
theme: jekyll-theme-minimal

#allow future dates
future: true